/**
 * Standardized Error Codes for RestOh Backend
 *
 * Used in error responses to enable frontend InlineAlert component
 * to provide better UX with specific handling for different error types.
 */

// === Reservations - Availability ===
const TABLES_UNAVAILABLE = 'TABLES_UNAVAILABLE';
const TABLE_NOT_FOUND = 'TABLE_NOT_FOUND';

// === Reservations - Capacity & Validation ===
const CAPACITY_EXCEEDED = 'CAPACITY_EXCEEDED';
const CAPACITY_INSUFFICIENT = 'CAPACITY_INSUFFICIENT';
const INVALID_TABLE_CAPACITY = 'INVALID_TABLE_CAPACITY';

// === Reservations - Timing ===
const RESERVATION_TOO_LATE = 'RESERVATION_TOO_LATE';
const MODIFICATION_TOO_LATE = 'MODIFICATION_TOO_LATE';
const CANCELLATION_TOO_LATE = 'CANCELLATION_TOO_LATE';

// === Reservations - Status ===
const RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND';
const RESERVATION_NOT_MODIFIABLE = 'RESERVATION_NOT_MODIFIABLE';
const RESERVATION_ALREADY_CANCELLED = 'RESERVATION_ALREADY_CANCELLED';

// === Authentication ===
const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
const AUTH_ACCOUNT_DELETED = 'AUTH_ACCOUNT_DELETED';
const AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE';

// === User Management ===
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const USER_ALREADY_DELETED = 'USER_ALREADY_DELETED';
const CANNOT_MODIFY_DELETED_ACCOUNT = 'CANNOT_MODIFY_DELETED_ACCOUNT';
const CANNOT_DELETE_OWN_ACCOUNT = 'CANNOT_DELETE_OWN_ACCOUNT';
const ADMIN_INVALID_CREDENTIALS = 'ADMIN_INVALID_CREDENTIALS';

// === Orders ===
const ORDER_EMPTY_ITEMS = 'ORDER_EMPTY_ITEMS';
const ORDER_INVALID_TYPE = 'ORDER_INVALID_TYPE';
const ORDER_MISSING_DELIVERY_ADDRESS = 'ORDER_MISSING_DELIVERY_ADDRESS';
const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
const ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS';
const PAYMENT_FAILED = 'PAYMENT_FAILED';
const MENU_ITEM_UNAVAILABLE = 'MENU_ITEM_UNAVAILABLE';

// === Generic ===
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const SERVER_ERROR = 'SERVER_ERROR';
const FORBIDDEN = 'FORBIDDEN';

module.exports = {
  // Reservations - Availability
  TABLES_UNAVAILABLE,
  TABLE_NOT_FOUND,

  // Reservations - Capacity & Validation
  CAPACITY_EXCEEDED,
  CAPACITY_INSUFFICIENT,
  INVALID_TABLE_CAPACITY,

  // Reservations - Timing
  RESERVATION_TOO_LATE,
  MODIFICATION_TOO_LATE,
  CANCELLATION_TOO_LATE,

  // Reservations - Status
  RESERVATION_NOT_FOUND,
  RESERVATION_NOT_MODIFIABLE,
  RESERVATION_ALREADY_CANCELLED,

  // Authentication
  AUTH_INVALID_CREDENTIALS,
  AUTH_ACCOUNT_DELETED,
  AUTH_ACCOUNT_INACTIVE,

  // User Management
  USER_NOT_FOUND,
  USER_ALREADY_DELETED,
  CANNOT_MODIFY_DELETED_ACCOUNT,
  CANNOT_DELETE_OWN_ACCOUNT,
  ADMIN_INVALID_CREDENTIALS,

  // Orders
  ORDER_EMPTY_ITEMS,
  ORDER_INVALID_TYPE,
  ORDER_MISSING_DELIVERY_ADDRESS,
  ORDER_NOT_FOUND,
  ORDER_INVALID_STATUS,
  PAYMENT_FAILED,
  MENU_ITEM_UNAVAILABLE,

  // Generic
  VALIDATION_ERROR,
  SERVER_ERROR,
  FORBIDDEN
};
