/**
 * Standardized Error Codes for RestOh Backend
 *
 * Used in error responses to enable frontend InlineAlert component
 * to provide better UX with specific handling for different error types.
 */

// === Reservations - Availability ===
const TABLES_UNAVAILABLE = 'TABLES_UNAVAILABLE';
const TABLE_NOT_FOUND = 'TABLE_NOT_FOUND';

// === Reservations - Capacity & Validation ===
const CAPACITY_EXCEEDED = 'CAPACITY_EXCEEDED';
const CAPACITY_INSUFFICIENT = 'CAPACITY_INSUFFICIENT';
const INVALID_TABLE_CAPACITY = 'INVALID_TABLE_CAPACITY';

// === Reservations - Timing ===
const RESERVATION_TOO_LATE = 'RESERVATION_TOO_LATE';
const MODIFICATION_TOO_LATE = 'MODIFICATION_TOO_LATE';
const CANCELLATION_TOO_LATE = 'CANCELLATION_TOO_LATE';

// === Reservations - Status ===
const RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND';
const RESERVATION_NOT_MODIFIABLE = 'RESERVATION_NOT_MODIFIABLE';
const RESERVATION_ALREADY_CANCELLED = 'RESERVATION_ALREADY_CANCELLED';

// === Authentication ===
const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
const AUTH_ACCOUNT_DELETED = 'AUTH_ACCOUNT_DELETED';
const AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE';

// === User Management ===
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const USER_ALREADY_DELETED = 'USER_ALREADY_DELETED';
const CANNOT_MODIFY_DELETED_ACCOUNT = 'CANNOT_MODIFY_DELETED_ACCOUNT';
const CANNOT_DELETE_OWN_ACCOUNT = 'CANNOT_DELETE_OWN_ACCOUNT';
const CANNOT_DEACTIVATE_OWN_ACCOUNT = 'CANNOT_DEACTIVATE_OWN_ACCOUNT';
const CANNOT_MODIFY_OWN_ROLE = 'CANNOT_MODIFY_OWN_ROLE';

// === Tables ===
const DATE_REQUIRED = 'DATE_REQUIRED';
const DATE_AND_SLOT_REQUIRED = 'DATE_AND_SLOT_REQUIRED';
const INVALID_SLOT_NUMBER = 'INVALID_SLOT_NUMBER';

// === Payment ===
const INVALID_AMOUNT = 'INVALID_AMOUNT';
const PAYMENT_INTENT_ID_REQUIRED = 'PAYMENT_INTENT_ID_REQUIRED';
const PAYMENT_INTENT_CREATION_FAILED = 'PAYMENT_INTENT_CREATION_FAILED';
const PAYMENT_NOT_COMPLETED = 'PAYMENT_NOT_COMPLETED';
const PAYMENT_CONFIRMATION_FAILED = 'PAYMENT_CONFIRMATION_FAILED';

// === Menu ===
const MENU_ITEM_NOT_FOUND = 'MENU_ITEM_NOT_FOUND';
const MENU_NOTHING_TO_UPDATE = 'MENU_NOTHING_TO_UPDATE';
const INVALID_RATING = 'INVALID_RATING';
const REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS';
const REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND';
const UNAUTHORIZED_REVIEW_UPDATE = 'UNAUTHORIZED_REVIEW_UPDATE';

// === Orders ===
const ORDER_EMPTY_ITEMS = 'ORDER_EMPTY_ITEMS';
const ORDER_INVALID_TYPE = 'ORDER_INVALID_TYPE';
const ORDER_MISSING_DELIVERY_ADDRESS = 'ORDER_MISSING_DELIVERY_ADDRESS';
const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
const ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS';
const PAYMENT_FAILED = 'PAYMENT_FAILED';
const MENU_ITEM_UNAVAILABLE = 'MENU_ITEM_UNAVAILABLE';

// === Contact ===
const CONTACT_MESSAGE_NOT_FOUND = 'CONTACT_MESSAGE_NOT_FOUND';
const INVALID_CONTACT_STATUS = 'INVALID_CONTACT_STATUS';

// === Generic ===
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const SERVER_ERROR = 'SERVER_ERROR';
const FORBIDDEN = 'FORBIDDEN';

module.exports = {
  // Reservations - Availability
  TABLES_UNAVAILABLE,
  TABLE_NOT_FOUND,

  // Reservations - Capacity & Validation
  CAPACITY_EXCEEDED,
  CAPACITY_INSUFFICIENT,
  INVALID_TABLE_CAPACITY,

  // Reservations - Timing
  RESERVATION_TOO_LATE,
  MODIFICATION_TOO_LATE,
  CANCELLATION_TOO_LATE,

  // Reservations - Status
  RESERVATION_NOT_FOUND,
  RESERVATION_NOT_MODIFIABLE,
  RESERVATION_ALREADY_CANCELLED,

  // Authentication
  AUTH_INVALID_CREDENTIALS,
  AUTH_ACCOUNT_DELETED,
  AUTH_ACCOUNT_INACTIVE,

  // User Management
  USER_NOT_FOUND,
  USER_ALREADY_DELETED,
  CANNOT_MODIFY_DELETED_ACCOUNT,
  CANNOT_DELETE_OWN_ACCOUNT,
  CANNOT_DEACTIVATE_OWN_ACCOUNT,
  CANNOT_MODIFY_OWN_ROLE,

  // Tables
  TABLE_NOT_FOUND,
  DATE_REQUIRED,
  DATE_AND_SLOT_REQUIRED,
  INVALID_SLOT_NUMBER,

  // Payment
  INVALID_AMOUNT,
  PAYMENT_INTENT_ID_REQUIRED,
  PAYMENT_INTENT_CREATION_FAILED,
  PAYMENT_NOT_COMPLETED,
  PAYMENT_CONFIRMATION_FAILED,

  // Menu
  MENU_ITEM_NOT_FOUND,
  MENU_NOTHING_TO_UPDATE,
  INVALID_RATING,
  REVIEW_ALREADY_EXISTS,
  REVIEW_NOT_FOUND,
  UNAUTHORIZED_REVIEW_UPDATE,

  // Orders
  ORDER_EMPTY_ITEMS,
  ORDER_INVALID_TYPE,
  ORDER_MISSING_DELIVERY_ADDRESS,
  ORDER_NOT_FOUND,
  ORDER_INVALID_STATUS,
  PAYMENT_FAILED,
  MENU_ITEM_UNAVAILABLE,

  // Contact
  CONTACT_MESSAGE_NOT_FOUND,
  INVALID_CONTACT_STATUS,

  // Generic
  VALIDATION_ERROR,
  SERVER_ERROR,
  FORBIDDEN
};
